// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZmrcbFKy4upxASvo17xeQL3YG7Vp0Xg',
    appId: '1:445417300823:web:ce8ea189b5ebf6b6565412',
    messagingSenderId: '445417300823',
    projectId: 'pawlife-84d14',
    authDomain: 'pawlife-84d14.firebaseapp.com',
    storageBucket: 'pawlife-84d14.firebasestorage.app',
    measurementId: 'G-MBE1KR12SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZ6UdJZfkEPm8Vb-XQaKADK2pQqfgpM0',
    appId: '1:445417300823:android:7f7cfa9333148cca565412',
    messagingSenderId: '445417300823',
    projectId: 'pawlife-84d14',
    storageBucket: 'pawlife-84d14.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohzzehBRCtcW0clSZABWEIiUdl5aq5Wg',
    appId: '1:445417300823:ios:0b6753d145a80f8b565412',
    messagingSenderId: '445417300823',
    projectId: 'pawlife-84d14',
    storageBucket: 'pawlife-84d14.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBohzzehBRCtcW0clSZABWEIiUdl5aq5Wg',
    appId: '1:445417300823:ios:0b6753d145a80f8b565412',
    messagingSenderId: '445417300823',
    projectId: 'pawlife-84d14',
    storageBucket: 'pawlife-84d14.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ZmrcbFKy4upxASvo17xeQL3YG7Vp0Xg',
    appId: '1:445417300823:web:7391b674da76c23c565412',
    messagingSenderId: '445417300823',
    projectId: 'pawlife-84d14',
    authDomain: 'pawlife-84d14.firebaseapp.com',
    storageBucket: 'pawlife-84d14.firebasestorage.app',
    measurementId: 'G-6WM5YWFZDD',
  );
}
